// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfdawwkfszsnnngkdcoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mZGF3d2tmc3pzbm5uZ2tkY29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDgzNTEsImV4cCI6MjA1NTIyNDM1MX0.P09swAwmHB6HbhnhoHkOaCAQfvRnxnRkCRf50Q7SH2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);