// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tthxywlxwuawecpaxbkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0aHh5d2x4d3Vhd2VjcGF4Ymt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4MDA3MzEsImV4cCI6MjA1NDM3NjczMX0.pRX4Bg2QpX1Y6PnxDMgObbcqcfvk_ca-aLJ31zDm71A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);